name: Angular Frontend - CI

on:
  pull_request:
    branches: [ main ]


jobs:
  ci:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./tour-of-heroes

    steps:
      - run: pwd
      
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Test project
        id: node-test
        run: ng test --watch=false --browsers=ChromeHeadless
