name: Angular Frontend - CI

on:
  pull_request:
    branches: [ main ]

    
env:
  frontend-path: tour-of-heroes

jobs:
  ci:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ env.frontend-path }}
        
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - run: pwd

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: '${{ env.frontend-path }}/package-lock.json'

      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Test project
        id: node-test
        run: ng test --watch=false --browsers=ChromeHeadless
